// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clmnzuqgybreszqphvgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsbW56dXFneWJyZXN6cXBodmd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NzkwMjgsImV4cCI6MjA2MTA1NTAyOH0.vVOmCFqJpXvra5MhN3kKnuodCXPuswrJx6QEzJ0Q1Mg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);